// flow-typed signature: f516d807fc98953d25da7f70504240e5
// flow-typed version: <<STUB>>/rambda_v^1.0.12/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rambda'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rambda' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rambda/__tests__/addIndex' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/adjust' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/any' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/append' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/filter' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/find' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/findIndex' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/flatten' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/forEach' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/indexOf' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/join' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/map' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/prepend' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/reduce' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/reverse' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/update' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/contains' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/drop' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/dropLast' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/general' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/head' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/includes' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/init' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/is' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/last' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/concat' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/endsWith' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/lastIndexOf' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/length' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/not' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/startsWith' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/toLower' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/toString' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/toUpper' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/trim' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/all' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/allPass' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/always' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/anyPass' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/both' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/complement' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/compose' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/curry' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/defaultTo' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/either' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/equals' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/flip' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/identity' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/ifElse' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/isNil' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/partialCurry' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/pipe' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/match' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/math/add' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/math/divide' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/math/modulo' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/math/multiply' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/math/subtract' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/none' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/dissoc' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/has' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/merge' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/omit' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/path' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/pathOr' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/pick' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/pickAll' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/pluck' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/prop' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/values' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/propEq' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/range' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/reject' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/repeat' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/replace' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/sort' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/sortBy' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/split' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/splitEvery' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/tail' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/take' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/takeLast' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/tap' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/test' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/times' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/type' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/uniq' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/uniqWith' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/without' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/add' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/adjust' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/any' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/append' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/compose' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/contains' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/drop' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/dropLast' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/equals' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/filter' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/find' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/findIndex' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/flatten' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/head' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/headString' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/index' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/indexOf' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/init' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/initString' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/last' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/map' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/match' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/merge' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/omit' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/path' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/pick' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/pipe' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/prop' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/propEq' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/range' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/reduce' {
  declare module.exports: any;
}

declare module 'rambda/dist/rambda.cjs' {
  declare module.exports: any;
}

declare module 'rambda/dist/rambda.esm' {
  declare module.exports: any;
}

declare module 'rambda/dist/rambda.umd' {
  declare module.exports: any;
}

declare module 'rambda/files/benchmark' {
  declare module.exports: any;
}

declare module 'rambda/files/browseByTag' {
  declare module.exports: any;
}

declare module 'rambda/files/createReadme' {
  declare module.exports: any;
}

declare module 'rambda/files/debug' {
  declare module.exports: any;
}

declare module 'rambda/files/lint' {
  declare module.exports: any;
}

declare module 'rambda/files/minify' {
  declare module.exports: any;
}

declare module 'rambda/files/rollup.config' {
  declare module.exports: any;
}

declare module 'rambda/lib/add' {
  declare module.exports: any;
}

declare module 'rambda/lib/addIndex' {
  declare module.exports: any;
}

declare module 'rambda/lib/adjust' {
  declare module.exports: any;
}

declare module 'rambda/lib/all' {
  declare module.exports: any;
}

declare module 'rambda/lib/allPass' {
  declare module.exports: any;
}

declare module 'rambda/lib/always' {
  declare module.exports: any;
}

declare module 'rambda/lib/any' {
  declare module.exports: any;
}

declare module 'rambda/lib/anyPass' {
  declare module.exports: any;
}

declare module 'rambda/lib/append' {
  declare module.exports: any;
}

declare module 'rambda/lib/both' {
  declare module.exports: any;
}

declare module 'rambda/lib/complement' {
  declare module.exports: any;
}

declare module 'rambda/lib/compose' {
  declare module.exports: any;
}

declare module 'rambda/lib/concat' {
  declare module.exports: any;
}

declare module 'rambda/lib/contains' {
  declare module.exports: any;
}

declare module 'rambda/lib/curry' {
  declare module.exports: any;
}

declare module 'rambda/lib/dec' {
  declare module.exports: any;
}

declare module 'rambda/lib/defaultTo' {
  declare module.exports: any;
}

declare module 'rambda/lib/dissoc' {
  declare module.exports: any;
}

declare module 'rambda/lib/divide' {
  declare module.exports: any;
}

declare module 'rambda/lib/drop' {
  declare module.exports: any;
}

declare module 'rambda/lib/dropLast' {
  declare module.exports: any;
}

declare module 'rambda/lib/either' {
  declare module.exports: any;
}

declare module 'rambda/lib/endsWith' {
  declare module.exports: any;
}

declare module 'rambda/lib/equals' {
  declare module.exports: any;
}

declare module 'rambda/lib/F' {
  declare module.exports: any;
}

declare module 'rambda/lib/filter' {
  declare module.exports: any;
}

declare module 'rambda/lib/find' {
  declare module.exports: any;
}

declare module 'rambda/lib/findIndex' {
  declare module.exports: any;
}

declare module 'rambda/lib/flatten' {
  declare module.exports: any;
}

declare module 'rambda/lib/flip' {
  declare module.exports: any;
}

declare module 'rambda/lib/forEach' {
  declare module.exports: any;
}

declare module 'rambda/lib/has' {
  declare module.exports: any;
}

declare module 'rambda/lib/head' {
  declare module.exports: any;
}

declare module 'rambda/lib/identity' {
  declare module.exports: any;
}

declare module 'rambda/lib/ifElse' {
  declare module.exports: any;
}

declare module 'rambda/lib/inc' {
  declare module.exports: any;
}

declare module 'rambda/lib/includes' {
  declare module.exports: any;
}

declare module 'rambda/lib/indexOf' {
  declare module.exports: any;
}

declare module 'rambda/lib/init' {
  declare module.exports: any;
}

declare module 'rambda/lib/internal/baseSlice' {
  declare module.exports: any;
}

declare module 'rambda/lib/is' {
  declare module.exports: any;
}

declare module 'rambda/lib/isNil' {
  declare module.exports: any;
}

declare module 'rambda/lib/join' {
  declare module.exports: any;
}

declare module 'rambda/lib/last' {
  declare module.exports: any;
}

declare module 'rambda/lib/lastIndexOf' {
  declare module.exports: any;
}

declare module 'rambda/lib/length' {
  declare module.exports: any;
}

declare module 'rambda/lib/map' {
  declare module.exports: any;
}

declare module 'rambda/lib/match' {
  declare module.exports: any;
}

declare module 'rambda/lib/merge' {
  declare module.exports: any;
}

declare module 'rambda/lib/modulo' {
  declare module.exports: any;
}

declare module 'rambda/lib/multiply' {
  declare module.exports: any;
}

declare module 'rambda/lib/none' {
  declare module.exports: any;
}

declare module 'rambda/lib/not' {
  declare module.exports: any;
}

declare module 'rambda/lib/omit' {
  declare module.exports: any;
}

declare module 'rambda/lib/partialCurry' {
  declare module.exports: any;
}

declare module 'rambda/lib/path' {
  declare module.exports: any;
}

declare module 'rambda/lib/pathOr' {
  declare module.exports: any;
}

declare module 'rambda/lib/pick' {
  declare module.exports: any;
}

declare module 'rambda/lib/pickAll' {
  declare module.exports: any;
}

declare module 'rambda/lib/pipe' {
  declare module.exports: any;
}

declare module 'rambda/lib/pluck' {
  declare module.exports: any;
}

declare module 'rambda/lib/prepend' {
  declare module.exports: any;
}

declare module 'rambda/lib/prop' {
  declare module.exports: any;
}

declare module 'rambda/lib/propEq' {
  declare module.exports: any;
}

declare module 'rambda/lib/range' {
  declare module.exports: any;
}

declare module 'rambda/lib/reduce' {
  declare module.exports: any;
}

declare module 'rambda/lib/reject' {
  declare module.exports: any;
}

declare module 'rambda/lib/repeat' {
  declare module.exports: any;
}

declare module 'rambda/lib/replace' {
  declare module.exports: any;
}

declare module 'rambda/lib/reverse' {
  declare module.exports: any;
}

declare module 'rambda/lib/sort' {
  declare module.exports: any;
}

declare module 'rambda/lib/sortBy' {
  declare module.exports: any;
}

declare module 'rambda/lib/split' {
  declare module.exports: any;
}

declare module 'rambda/lib/splitEvery' {
  declare module.exports: any;
}

declare module 'rambda/lib/startsWith' {
  declare module.exports: any;
}

declare module 'rambda/lib/subtract' {
  declare module.exports: any;
}

declare module 'rambda/lib/T' {
  declare module.exports: any;
}

declare module 'rambda/lib/tail' {
  declare module.exports: any;
}

declare module 'rambda/lib/take' {
  declare module.exports: any;
}

declare module 'rambda/lib/takeLast' {
  declare module.exports: any;
}

declare module 'rambda/lib/tap' {
  declare module.exports: any;
}

declare module 'rambda/lib/test' {
  declare module.exports: any;
}

declare module 'rambda/lib/times' {
  declare module.exports: any;
}

declare module 'rambda/lib/toLower' {
  declare module.exports: any;
}

declare module 'rambda/lib/toString' {
  declare module.exports: any;
}

declare module 'rambda/lib/toUpper' {
  declare module.exports: any;
}

declare module 'rambda/lib/trim' {
  declare module.exports: any;
}

declare module 'rambda/lib/type' {
  declare module.exports: any;
}

declare module 'rambda/lib/uniq' {
  declare module.exports: any;
}

declare module 'rambda/lib/uniqWith' {
  declare module.exports: any;
}

declare module 'rambda/lib/update' {
  declare module.exports: any;
}

declare module 'rambda/lib/values' {
  declare module.exports: any;
}

declare module 'rambda/lib/without' {
  declare module.exports: any;
}

declare module 'rambda/modules/add' {
  declare module.exports: any;
}

declare module 'rambda/modules/addIndex' {
  declare module.exports: any;
}

declare module 'rambda/modules/adjust' {
  declare module.exports: any;
}

declare module 'rambda/modules/all' {
  declare module.exports: any;
}

declare module 'rambda/modules/allPass' {
  declare module.exports: any;
}

declare module 'rambda/modules/always' {
  declare module.exports: any;
}

declare module 'rambda/modules/any' {
  declare module.exports: any;
}

declare module 'rambda/modules/anyPass' {
  declare module.exports: any;
}

declare module 'rambda/modules/append' {
  declare module.exports: any;
}

declare module 'rambda/modules/both' {
  declare module.exports: any;
}

declare module 'rambda/modules/complement' {
  declare module.exports: any;
}

declare module 'rambda/modules/compose' {
  declare module.exports: any;
}

declare module 'rambda/modules/concat' {
  declare module.exports: any;
}

declare module 'rambda/modules/contains' {
  declare module.exports: any;
}

declare module 'rambda/modules/curry' {
  declare module.exports: any;
}

declare module 'rambda/modules/dec' {
  declare module.exports: any;
}

declare module 'rambda/modules/defaultTo' {
  declare module.exports: any;
}

declare module 'rambda/modules/dissoc' {
  declare module.exports: any;
}

declare module 'rambda/modules/divide' {
  declare module.exports: any;
}

declare module 'rambda/modules/drop' {
  declare module.exports: any;
}

declare module 'rambda/modules/dropLast' {
  declare module.exports: any;
}

declare module 'rambda/modules/either' {
  declare module.exports: any;
}

declare module 'rambda/modules/endsWith' {
  declare module.exports: any;
}

declare module 'rambda/modules/equals' {
  declare module.exports: any;
}

declare module 'rambda/modules/F' {
  declare module.exports: any;
}

declare module 'rambda/modules/filter' {
  declare module.exports: any;
}

declare module 'rambda/modules/find' {
  declare module.exports: any;
}

declare module 'rambda/modules/findIndex' {
  declare module.exports: any;
}

declare module 'rambda/modules/flatten' {
  declare module.exports: any;
}

declare module 'rambda/modules/flip' {
  declare module.exports: any;
}

declare module 'rambda/modules/forEach' {
  declare module.exports: any;
}

declare module 'rambda/modules/has' {
  declare module.exports: any;
}

declare module 'rambda/modules/head' {
  declare module.exports: any;
}

declare module 'rambda/modules/identity' {
  declare module.exports: any;
}

declare module 'rambda/modules/ifElse' {
  declare module.exports: any;
}

declare module 'rambda/modules/inc' {
  declare module.exports: any;
}

declare module 'rambda/modules/includes' {
  declare module.exports: any;
}

declare module 'rambda/modules/indexOf' {
  declare module.exports: any;
}

declare module 'rambda/modules/init' {
  declare module.exports: any;
}

declare module 'rambda/modules/internal/baseSlice' {
  declare module.exports: any;
}

declare module 'rambda/modules/is' {
  declare module.exports: any;
}

declare module 'rambda/modules/isNil' {
  declare module.exports: any;
}

declare module 'rambda/modules/join' {
  declare module.exports: any;
}

declare module 'rambda/modules/last' {
  declare module.exports: any;
}

declare module 'rambda/modules/lastIndexOf' {
  declare module.exports: any;
}

declare module 'rambda/modules/length' {
  declare module.exports: any;
}

declare module 'rambda/modules/map' {
  declare module.exports: any;
}

declare module 'rambda/modules/match' {
  declare module.exports: any;
}

declare module 'rambda/modules/merge' {
  declare module.exports: any;
}

declare module 'rambda/modules/modulo' {
  declare module.exports: any;
}

declare module 'rambda/modules/multiply' {
  declare module.exports: any;
}

declare module 'rambda/modules/none' {
  declare module.exports: any;
}

declare module 'rambda/modules/not' {
  declare module.exports: any;
}

declare module 'rambda/modules/omit' {
  declare module.exports: any;
}

declare module 'rambda/modules/partialCurry' {
  declare module.exports: any;
}

declare module 'rambda/modules/path' {
  declare module.exports: any;
}

declare module 'rambda/modules/pathOr' {
  declare module.exports: any;
}

declare module 'rambda/modules/pick' {
  declare module.exports: any;
}

declare module 'rambda/modules/pickAll' {
  declare module.exports: any;
}

declare module 'rambda/modules/pipe' {
  declare module.exports: any;
}

declare module 'rambda/modules/pluck' {
  declare module.exports: any;
}

declare module 'rambda/modules/prepend' {
  declare module.exports: any;
}

declare module 'rambda/modules/prop' {
  declare module.exports: any;
}

declare module 'rambda/modules/propEq' {
  declare module.exports: any;
}

declare module 'rambda/modules/range' {
  declare module.exports: any;
}

declare module 'rambda/modules/reduce' {
  declare module.exports: any;
}

declare module 'rambda/modules/reject' {
  declare module.exports: any;
}

declare module 'rambda/modules/repeat' {
  declare module.exports: any;
}

declare module 'rambda/modules/replace' {
  declare module.exports: any;
}

declare module 'rambda/modules/reverse' {
  declare module.exports: any;
}

declare module 'rambda/modules/sort' {
  declare module.exports: any;
}

declare module 'rambda/modules/sortBy' {
  declare module.exports: any;
}

declare module 'rambda/modules/split' {
  declare module.exports: any;
}

declare module 'rambda/modules/splitEvery' {
  declare module.exports: any;
}

declare module 'rambda/modules/startsWith' {
  declare module.exports: any;
}

declare module 'rambda/modules/subtract' {
  declare module.exports: any;
}

declare module 'rambda/modules/T' {
  declare module.exports: any;
}

declare module 'rambda/modules/tail' {
  declare module.exports: any;
}

declare module 'rambda/modules/take' {
  declare module.exports: any;
}

declare module 'rambda/modules/takeLast' {
  declare module.exports: any;
}

declare module 'rambda/modules/tap' {
  declare module.exports: any;
}

declare module 'rambda/modules/test' {
  declare module.exports: any;
}

declare module 'rambda/modules/times' {
  declare module.exports: any;
}

declare module 'rambda/modules/toLower' {
  declare module.exports: any;
}

declare module 'rambda/modules/toString' {
  declare module.exports: any;
}

declare module 'rambda/modules/toUpper' {
  declare module.exports: any;
}

declare module 'rambda/modules/trim' {
  declare module.exports: any;
}

declare module 'rambda/modules/type' {
  declare module.exports: any;
}

declare module 'rambda/modules/uniq' {
  declare module.exports: any;
}

declare module 'rambda/modules/uniqWith' {
  declare module.exports: any;
}

declare module 'rambda/modules/update' {
  declare module.exports: any;
}

declare module 'rambda/modules/values' {
  declare module.exports: any;
}

declare module 'rambda/modules/without' {
  declare module.exports: any;
}

declare module 'rambda/rambda' {
  declare module.exports: any;
}

declare module 'rambda/webVersion' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rambda/__tests__/addIndex.js' {
  declare module.exports: $Exports<'rambda/__tests__/addIndex'>;
}
declare module 'rambda/__tests__/array/adjust.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/adjust'>;
}
declare module 'rambda/__tests__/array/any.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/any'>;
}
declare module 'rambda/__tests__/array/append.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/append'>;
}
declare module 'rambda/__tests__/array/filter.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/filter'>;
}
declare module 'rambda/__tests__/array/find.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/find'>;
}
declare module 'rambda/__tests__/array/findIndex.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/findIndex'>;
}
declare module 'rambda/__tests__/array/flatten.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/flatten'>;
}
declare module 'rambda/__tests__/array/forEach.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/forEach'>;
}
declare module 'rambda/__tests__/array/indexOf.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/indexOf'>;
}
declare module 'rambda/__tests__/array/join.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/join'>;
}
declare module 'rambda/__tests__/array/map.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/map'>;
}
declare module 'rambda/__tests__/array/prepend.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/prepend'>;
}
declare module 'rambda/__tests__/array/reduce.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/reduce'>;
}
declare module 'rambda/__tests__/array/reverse.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/reverse'>;
}
declare module 'rambda/__tests__/array/update.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/update'>;
}
declare module 'rambda/__tests__/contains.js' {
  declare module.exports: $Exports<'rambda/__tests__/contains'>;
}
declare module 'rambda/__tests__/drop.js' {
  declare module.exports: $Exports<'rambda/__tests__/drop'>;
}
declare module 'rambda/__tests__/dropLast.js' {
  declare module.exports: $Exports<'rambda/__tests__/dropLast'>;
}
declare module 'rambda/__tests__/general.js' {
  declare module.exports: $Exports<'rambda/__tests__/general'>;
}
declare module 'rambda/__tests__/head.js' {
  declare module.exports: $Exports<'rambda/__tests__/head'>;
}
declare module 'rambda/__tests__/includes.js' {
  declare module.exports: $Exports<'rambda/__tests__/includes'>;
}
declare module 'rambda/__tests__/init.js' {
  declare module.exports: $Exports<'rambda/__tests__/init'>;
}
declare module 'rambda/__tests__/is.js' {
  declare module.exports: $Exports<'rambda/__tests__/is'>;
}
declare module 'rambda/__tests__/last.js' {
  declare module.exports: $Exports<'rambda/__tests__/last'>;
}
declare module 'rambda/__tests__/lazy/concat.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/concat'>;
}
declare module 'rambda/__tests__/lazy/endsWith.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/endsWith'>;
}
declare module 'rambda/__tests__/lazy/lastIndexOf.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/lastIndexOf'>;
}
declare module 'rambda/__tests__/lazy/length.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/length'>;
}
declare module 'rambda/__tests__/lazy/not.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/not'>;
}
declare module 'rambda/__tests__/lazy/startsWith.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/startsWith'>;
}
declare module 'rambda/__tests__/lazy/toLower.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/toLower'>;
}
declare module 'rambda/__tests__/lazy/toString.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/toString'>;
}
declare module 'rambda/__tests__/lazy/toUpper.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/toUpper'>;
}
declare module 'rambda/__tests__/lazy/trim.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/trim'>;
}
declare module 'rambda/__tests__/logic/all.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/all'>;
}
declare module 'rambda/__tests__/logic/allPass.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/allPass'>;
}
declare module 'rambda/__tests__/logic/always.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/always'>;
}
declare module 'rambda/__tests__/logic/anyPass.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/anyPass'>;
}
declare module 'rambda/__tests__/logic/both.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/both'>;
}
declare module 'rambda/__tests__/logic/complement.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/complement'>;
}
declare module 'rambda/__tests__/logic/compose.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/compose'>;
}
declare module 'rambda/__tests__/logic/curry.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/curry'>;
}
declare module 'rambda/__tests__/logic/defaultTo.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/defaultTo'>;
}
declare module 'rambda/__tests__/logic/either.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/either'>;
}
declare module 'rambda/__tests__/logic/equals.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/equals'>;
}
declare module 'rambda/__tests__/logic/flip.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/flip'>;
}
declare module 'rambda/__tests__/logic/identity.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/identity'>;
}
declare module 'rambda/__tests__/logic/ifElse.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/ifElse'>;
}
declare module 'rambda/__tests__/logic/isNil.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/isNil'>;
}
declare module 'rambda/__tests__/logic/partialCurry.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/partialCurry'>;
}
declare module 'rambda/__tests__/logic/pipe.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/pipe'>;
}
declare module 'rambda/__tests__/match.js' {
  declare module.exports: $Exports<'rambda/__tests__/match'>;
}
declare module 'rambda/__tests__/math/add.js' {
  declare module.exports: $Exports<'rambda/__tests__/math/add'>;
}
declare module 'rambda/__tests__/math/divide.js' {
  declare module.exports: $Exports<'rambda/__tests__/math/divide'>;
}
declare module 'rambda/__tests__/math/modulo.js' {
  declare module.exports: $Exports<'rambda/__tests__/math/modulo'>;
}
declare module 'rambda/__tests__/math/multiply.js' {
  declare module.exports: $Exports<'rambda/__tests__/math/multiply'>;
}
declare module 'rambda/__tests__/math/subtract.js' {
  declare module.exports: $Exports<'rambda/__tests__/math/subtract'>;
}
declare module 'rambda/__tests__/none.js' {
  declare module.exports: $Exports<'rambda/__tests__/none'>;
}
declare module 'rambda/__tests__/object/dissoc.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/dissoc'>;
}
declare module 'rambda/__tests__/object/has.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/has'>;
}
declare module 'rambda/__tests__/object/merge.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/merge'>;
}
declare module 'rambda/__tests__/object/omit.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/omit'>;
}
declare module 'rambda/__tests__/object/path.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/path'>;
}
declare module 'rambda/__tests__/object/pathOr.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/pathOr'>;
}
declare module 'rambda/__tests__/object/pick.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/pick'>;
}
declare module 'rambda/__tests__/object/pickAll.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/pickAll'>;
}
declare module 'rambda/__tests__/object/pluck.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/pluck'>;
}
declare module 'rambda/__tests__/object/prop.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/prop'>;
}
declare module 'rambda/__tests__/object/values.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/values'>;
}
declare module 'rambda/__tests__/propEq.js' {
  declare module.exports: $Exports<'rambda/__tests__/propEq'>;
}
declare module 'rambda/__tests__/range.js' {
  declare module.exports: $Exports<'rambda/__tests__/range'>;
}
declare module 'rambda/__tests__/reject.js' {
  declare module.exports: $Exports<'rambda/__tests__/reject'>;
}
declare module 'rambda/__tests__/repeat.js' {
  declare module.exports: $Exports<'rambda/__tests__/repeat'>;
}
declare module 'rambda/__tests__/replace.js' {
  declare module.exports: $Exports<'rambda/__tests__/replace'>;
}
declare module 'rambda/__tests__/sort.js' {
  declare module.exports: $Exports<'rambda/__tests__/sort'>;
}
declare module 'rambda/__tests__/sortBy.js' {
  declare module.exports: $Exports<'rambda/__tests__/sortBy'>;
}
declare module 'rambda/__tests__/split.js' {
  declare module.exports: $Exports<'rambda/__tests__/split'>;
}
declare module 'rambda/__tests__/splitEvery.js' {
  declare module.exports: $Exports<'rambda/__tests__/splitEvery'>;
}
declare module 'rambda/__tests__/tail.js' {
  declare module.exports: $Exports<'rambda/__tests__/tail'>;
}
declare module 'rambda/__tests__/take.js' {
  declare module.exports: $Exports<'rambda/__tests__/take'>;
}
declare module 'rambda/__tests__/takeLast.js' {
  declare module.exports: $Exports<'rambda/__tests__/takeLast'>;
}
declare module 'rambda/__tests__/tap.js' {
  declare module.exports: $Exports<'rambda/__tests__/tap'>;
}
declare module 'rambda/__tests__/test.js' {
  declare module.exports: $Exports<'rambda/__tests__/test'>;
}
declare module 'rambda/__tests__/times.js' {
  declare module.exports: $Exports<'rambda/__tests__/times'>;
}
declare module 'rambda/__tests__/type.js' {
  declare module.exports: $Exports<'rambda/__tests__/type'>;
}
declare module 'rambda/__tests__/uniq.js' {
  declare module.exports: $Exports<'rambda/__tests__/uniq'>;
}
declare module 'rambda/__tests__/uniqWith.js' {
  declare module.exports: $Exports<'rambda/__tests__/uniqWith'>;
}
declare module 'rambda/__tests__/without.js' {
  declare module.exports: $Exports<'rambda/__tests__/without'>;
}
declare module 'rambda/benchmarks/add.js' {
  declare module.exports: $Exports<'rambda/benchmarks/add'>;
}
declare module 'rambda/benchmarks/adjust.js' {
  declare module.exports: $Exports<'rambda/benchmarks/adjust'>;
}
declare module 'rambda/benchmarks/any.js' {
  declare module.exports: $Exports<'rambda/benchmarks/any'>;
}
declare module 'rambda/benchmarks/append.js' {
  declare module.exports: $Exports<'rambda/benchmarks/append'>;
}
declare module 'rambda/benchmarks/compose.js' {
  declare module.exports: $Exports<'rambda/benchmarks/compose'>;
}
declare module 'rambda/benchmarks/contains.js' {
  declare module.exports: $Exports<'rambda/benchmarks/contains'>;
}
declare module 'rambda/benchmarks/drop.js' {
  declare module.exports: $Exports<'rambda/benchmarks/drop'>;
}
declare module 'rambda/benchmarks/dropLast.js' {
  declare module.exports: $Exports<'rambda/benchmarks/dropLast'>;
}
declare module 'rambda/benchmarks/equals.js' {
  declare module.exports: $Exports<'rambda/benchmarks/equals'>;
}
declare module 'rambda/benchmarks/filter.js' {
  declare module.exports: $Exports<'rambda/benchmarks/filter'>;
}
declare module 'rambda/benchmarks/find.js' {
  declare module.exports: $Exports<'rambda/benchmarks/find'>;
}
declare module 'rambda/benchmarks/findIndex.js' {
  declare module.exports: $Exports<'rambda/benchmarks/findIndex'>;
}
declare module 'rambda/benchmarks/flatten.js' {
  declare module.exports: $Exports<'rambda/benchmarks/flatten'>;
}
declare module 'rambda/benchmarks/head.js' {
  declare module.exports: $Exports<'rambda/benchmarks/head'>;
}
declare module 'rambda/benchmarks/headString.js' {
  declare module.exports: $Exports<'rambda/benchmarks/headString'>;
}
declare module 'rambda/benchmarks/index.js' {
  declare module.exports: $Exports<'rambda/benchmarks/index'>;
}
declare module 'rambda/benchmarks/indexOf.js' {
  declare module.exports: $Exports<'rambda/benchmarks/indexOf'>;
}
declare module 'rambda/benchmarks/init.js' {
  declare module.exports: $Exports<'rambda/benchmarks/init'>;
}
declare module 'rambda/benchmarks/initString.js' {
  declare module.exports: $Exports<'rambda/benchmarks/initString'>;
}
declare module 'rambda/benchmarks/last.js' {
  declare module.exports: $Exports<'rambda/benchmarks/last'>;
}
declare module 'rambda/benchmarks/map.js' {
  declare module.exports: $Exports<'rambda/benchmarks/map'>;
}
declare module 'rambda/benchmarks/match.js' {
  declare module.exports: $Exports<'rambda/benchmarks/match'>;
}
declare module 'rambda/benchmarks/merge.js' {
  declare module.exports: $Exports<'rambda/benchmarks/merge'>;
}
declare module 'rambda/benchmarks/omit.js' {
  declare module.exports: $Exports<'rambda/benchmarks/omit'>;
}
declare module 'rambda/benchmarks/path.js' {
  declare module.exports: $Exports<'rambda/benchmarks/path'>;
}
declare module 'rambda/benchmarks/pick.js' {
  declare module.exports: $Exports<'rambda/benchmarks/pick'>;
}
declare module 'rambda/benchmarks/pipe.js' {
  declare module.exports: $Exports<'rambda/benchmarks/pipe'>;
}
declare module 'rambda/benchmarks/prop.js' {
  declare module.exports: $Exports<'rambda/benchmarks/prop'>;
}
declare module 'rambda/benchmarks/propEq.js' {
  declare module.exports: $Exports<'rambda/benchmarks/propEq'>;
}
declare module 'rambda/benchmarks/range.js' {
  declare module.exports: $Exports<'rambda/benchmarks/range'>;
}
declare module 'rambda/benchmarks/reduce.js' {
  declare module.exports: $Exports<'rambda/benchmarks/reduce'>;
}
declare module 'rambda/dist/rambda.cjs.js' {
  declare module.exports: $Exports<'rambda/dist/rambda.cjs'>;
}
declare module 'rambda/dist/rambda.esm.js' {
  declare module.exports: $Exports<'rambda/dist/rambda.esm'>;
}
declare module 'rambda/dist/rambda.umd.js' {
  declare module.exports: $Exports<'rambda/dist/rambda.umd'>;
}
declare module 'rambda/files/benchmark.js' {
  declare module.exports: $Exports<'rambda/files/benchmark'>;
}
declare module 'rambda/files/browseByTag.js' {
  declare module.exports: $Exports<'rambda/files/browseByTag'>;
}
declare module 'rambda/files/createReadme.js' {
  declare module.exports: $Exports<'rambda/files/createReadme'>;
}
declare module 'rambda/files/debug.js' {
  declare module.exports: $Exports<'rambda/files/debug'>;
}
declare module 'rambda/files/lint.js' {
  declare module.exports: $Exports<'rambda/files/lint'>;
}
declare module 'rambda/files/minify.js' {
  declare module.exports: $Exports<'rambda/files/minify'>;
}
declare module 'rambda/files/rollup.config.js' {
  declare module.exports: $Exports<'rambda/files/rollup.config'>;
}
declare module 'rambda/lib/add.js' {
  declare module.exports: $Exports<'rambda/lib/add'>;
}
declare module 'rambda/lib/addIndex.js' {
  declare module.exports: $Exports<'rambda/lib/addIndex'>;
}
declare module 'rambda/lib/adjust.js' {
  declare module.exports: $Exports<'rambda/lib/adjust'>;
}
declare module 'rambda/lib/all.js' {
  declare module.exports: $Exports<'rambda/lib/all'>;
}
declare module 'rambda/lib/allPass.js' {
  declare module.exports: $Exports<'rambda/lib/allPass'>;
}
declare module 'rambda/lib/always.js' {
  declare module.exports: $Exports<'rambda/lib/always'>;
}
declare module 'rambda/lib/any.js' {
  declare module.exports: $Exports<'rambda/lib/any'>;
}
declare module 'rambda/lib/anyPass.js' {
  declare module.exports: $Exports<'rambda/lib/anyPass'>;
}
declare module 'rambda/lib/append.js' {
  declare module.exports: $Exports<'rambda/lib/append'>;
}
declare module 'rambda/lib/both.js' {
  declare module.exports: $Exports<'rambda/lib/both'>;
}
declare module 'rambda/lib/complement.js' {
  declare module.exports: $Exports<'rambda/lib/complement'>;
}
declare module 'rambda/lib/compose.js' {
  declare module.exports: $Exports<'rambda/lib/compose'>;
}
declare module 'rambda/lib/concat.js' {
  declare module.exports: $Exports<'rambda/lib/concat'>;
}
declare module 'rambda/lib/contains.js' {
  declare module.exports: $Exports<'rambda/lib/contains'>;
}
declare module 'rambda/lib/curry.js' {
  declare module.exports: $Exports<'rambda/lib/curry'>;
}
declare module 'rambda/lib/dec.js' {
  declare module.exports: $Exports<'rambda/lib/dec'>;
}
declare module 'rambda/lib/defaultTo.js' {
  declare module.exports: $Exports<'rambda/lib/defaultTo'>;
}
declare module 'rambda/lib/dissoc.js' {
  declare module.exports: $Exports<'rambda/lib/dissoc'>;
}
declare module 'rambda/lib/divide.js' {
  declare module.exports: $Exports<'rambda/lib/divide'>;
}
declare module 'rambda/lib/drop.js' {
  declare module.exports: $Exports<'rambda/lib/drop'>;
}
declare module 'rambda/lib/dropLast.js' {
  declare module.exports: $Exports<'rambda/lib/dropLast'>;
}
declare module 'rambda/lib/either.js' {
  declare module.exports: $Exports<'rambda/lib/either'>;
}
declare module 'rambda/lib/endsWith.js' {
  declare module.exports: $Exports<'rambda/lib/endsWith'>;
}
declare module 'rambda/lib/equals.js' {
  declare module.exports: $Exports<'rambda/lib/equals'>;
}
declare module 'rambda/lib/F.js' {
  declare module.exports: $Exports<'rambda/lib/F'>;
}
declare module 'rambda/lib/filter.js' {
  declare module.exports: $Exports<'rambda/lib/filter'>;
}
declare module 'rambda/lib/find.js' {
  declare module.exports: $Exports<'rambda/lib/find'>;
}
declare module 'rambda/lib/findIndex.js' {
  declare module.exports: $Exports<'rambda/lib/findIndex'>;
}
declare module 'rambda/lib/flatten.js' {
  declare module.exports: $Exports<'rambda/lib/flatten'>;
}
declare module 'rambda/lib/flip.js' {
  declare module.exports: $Exports<'rambda/lib/flip'>;
}
declare module 'rambda/lib/forEach.js' {
  declare module.exports: $Exports<'rambda/lib/forEach'>;
}
declare module 'rambda/lib/has.js' {
  declare module.exports: $Exports<'rambda/lib/has'>;
}
declare module 'rambda/lib/head.js' {
  declare module.exports: $Exports<'rambda/lib/head'>;
}
declare module 'rambda/lib/identity.js' {
  declare module.exports: $Exports<'rambda/lib/identity'>;
}
declare module 'rambda/lib/ifElse.js' {
  declare module.exports: $Exports<'rambda/lib/ifElse'>;
}
declare module 'rambda/lib/inc.js' {
  declare module.exports: $Exports<'rambda/lib/inc'>;
}
declare module 'rambda/lib/includes.js' {
  declare module.exports: $Exports<'rambda/lib/includes'>;
}
declare module 'rambda/lib/indexOf.js' {
  declare module.exports: $Exports<'rambda/lib/indexOf'>;
}
declare module 'rambda/lib/init.js' {
  declare module.exports: $Exports<'rambda/lib/init'>;
}
declare module 'rambda/lib/internal/baseSlice.js' {
  declare module.exports: $Exports<'rambda/lib/internal/baseSlice'>;
}
declare module 'rambda/lib/is.js' {
  declare module.exports: $Exports<'rambda/lib/is'>;
}
declare module 'rambda/lib/isNil.js' {
  declare module.exports: $Exports<'rambda/lib/isNil'>;
}
declare module 'rambda/lib/join.js' {
  declare module.exports: $Exports<'rambda/lib/join'>;
}
declare module 'rambda/lib/last.js' {
  declare module.exports: $Exports<'rambda/lib/last'>;
}
declare module 'rambda/lib/lastIndexOf.js' {
  declare module.exports: $Exports<'rambda/lib/lastIndexOf'>;
}
declare module 'rambda/lib/length.js' {
  declare module.exports: $Exports<'rambda/lib/length'>;
}
declare module 'rambda/lib/map.js' {
  declare module.exports: $Exports<'rambda/lib/map'>;
}
declare module 'rambda/lib/match.js' {
  declare module.exports: $Exports<'rambda/lib/match'>;
}
declare module 'rambda/lib/merge.js' {
  declare module.exports: $Exports<'rambda/lib/merge'>;
}
declare module 'rambda/lib/modulo.js' {
  declare module.exports: $Exports<'rambda/lib/modulo'>;
}
declare module 'rambda/lib/multiply.js' {
  declare module.exports: $Exports<'rambda/lib/multiply'>;
}
declare module 'rambda/lib/none.js' {
  declare module.exports: $Exports<'rambda/lib/none'>;
}
declare module 'rambda/lib/not.js' {
  declare module.exports: $Exports<'rambda/lib/not'>;
}
declare module 'rambda/lib/omit.js' {
  declare module.exports: $Exports<'rambda/lib/omit'>;
}
declare module 'rambda/lib/partialCurry.js' {
  declare module.exports: $Exports<'rambda/lib/partialCurry'>;
}
declare module 'rambda/lib/path.js' {
  declare module.exports: $Exports<'rambda/lib/path'>;
}
declare module 'rambda/lib/pathOr.js' {
  declare module.exports: $Exports<'rambda/lib/pathOr'>;
}
declare module 'rambda/lib/pick.js' {
  declare module.exports: $Exports<'rambda/lib/pick'>;
}
declare module 'rambda/lib/pickAll.js' {
  declare module.exports: $Exports<'rambda/lib/pickAll'>;
}
declare module 'rambda/lib/pipe.js' {
  declare module.exports: $Exports<'rambda/lib/pipe'>;
}
declare module 'rambda/lib/pluck.js' {
  declare module.exports: $Exports<'rambda/lib/pluck'>;
}
declare module 'rambda/lib/prepend.js' {
  declare module.exports: $Exports<'rambda/lib/prepend'>;
}
declare module 'rambda/lib/prop.js' {
  declare module.exports: $Exports<'rambda/lib/prop'>;
}
declare module 'rambda/lib/propEq.js' {
  declare module.exports: $Exports<'rambda/lib/propEq'>;
}
declare module 'rambda/lib/range.js' {
  declare module.exports: $Exports<'rambda/lib/range'>;
}
declare module 'rambda/lib/reduce.js' {
  declare module.exports: $Exports<'rambda/lib/reduce'>;
}
declare module 'rambda/lib/reject.js' {
  declare module.exports: $Exports<'rambda/lib/reject'>;
}
declare module 'rambda/lib/repeat.js' {
  declare module.exports: $Exports<'rambda/lib/repeat'>;
}
declare module 'rambda/lib/replace.js' {
  declare module.exports: $Exports<'rambda/lib/replace'>;
}
declare module 'rambda/lib/reverse.js' {
  declare module.exports: $Exports<'rambda/lib/reverse'>;
}
declare module 'rambda/lib/sort.js' {
  declare module.exports: $Exports<'rambda/lib/sort'>;
}
declare module 'rambda/lib/sortBy.js' {
  declare module.exports: $Exports<'rambda/lib/sortBy'>;
}
declare module 'rambda/lib/split.js' {
  declare module.exports: $Exports<'rambda/lib/split'>;
}
declare module 'rambda/lib/splitEvery.js' {
  declare module.exports: $Exports<'rambda/lib/splitEvery'>;
}
declare module 'rambda/lib/startsWith.js' {
  declare module.exports: $Exports<'rambda/lib/startsWith'>;
}
declare module 'rambda/lib/subtract.js' {
  declare module.exports: $Exports<'rambda/lib/subtract'>;
}
declare module 'rambda/lib/T.js' {
  declare module.exports: $Exports<'rambda/lib/T'>;
}
declare module 'rambda/lib/tail.js' {
  declare module.exports: $Exports<'rambda/lib/tail'>;
}
declare module 'rambda/lib/take.js' {
  declare module.exports: $Exports<'rambda/lib/take'>;
}
declare module 'rambda/lib/takeLast.js' {
  declare module.exports: $Exports<'rambda/lib/takeLast'>;
}
declare module 'rambda/lib/tap.js' {
  declare module.exports: $Exports<'rambda/lib/tap'>;
}
declare module 'rambda/lib/test.js' {
  declare module.exports: $Exports<'rambda/lib/test'>;
}
declare module 'rambda/lib/times.js' {
  declare module.exports: $Exports<'rambda/lib/times'>;
}
declare module 'rambda/lib/toLower.js' {
  declare module.exports: $Exports<'rambda/lib/toLower'>;
}
declare module 'rambda/lib/toString.js' {
  declare module.exports: $Exports<'rambda/lib/toString'>;
}
declare module 'rambda/lib/toUpper.js' {
  declare module.exports: $Exports<'rambda/lib/toUpper'>;
}
declare module 'rambda/lib/trim.js' {
  declare module.exports: $Exports<'rambda/lib/trim'>;
}
declare module 'rambda/lib/type.js' {
  declare module.exports: $Exports<'rambda/lib/type'>;
}
declare module 'rambda/lib/uniq.js' {
  declare module.exports: $Exports<'rambda/lib/uniq'>;
}
declare module 'rambda/lib/uniqWith.js' {
  declare module.exports: $Exports<'rambda/lib/uniqWith'>;
}
declare module 'rambda/lib/update.js' {
  declare module.exports: $Exports<'rambda/lib/update'>;
}
declare module 'rambda/lib/values.js' {
  declare module.exports: $Exports<'rambda/lib/values'>;
}
declare module 'rambda/lib/without.js' {
  declare module.exports: $Exports<'rambda/lib/without'>;
}
declare module 'rambda/modules/add.js' {
  declare module.exports: $Exports<'rambda/modules/add'>;
}
declare module 'rambda/modules/addIndex.js' {
  declare module.exports: $Exports<'rambda/modules/addIndex'>;
}
declare module 'rambda/modules/adjust.js' {
  declare module.exports: $Exports<'rambda/modules/adjust'>;
}
declare module 'rambda/modules/all.js' {
  declare module.exports: $Exports<'rambda/modules/all'>;
}
declare module 'rambda/modules/allPass.js' {
  declare module.exports: $Exports<'rambda/modules/allPass'>;
}
declare module 'rambda/modules/always.js' {
  declare module.exports: $Exports<'rambda/modules/always'>;
}
declare module 'rambda/modules/any.js' {
  declare module.exports: $Exports<'rambda/modules/any'>;
}
declare module 'rambda/modules/anyPass.js' {
  declare module.exports: $Exports<'rambda/modules/anyPass'>;
}
declare module 'rambda/modules/append.js' {
  declare module.exports: $Exports<'rambda/modules/append'>;
}
declare module 'rambda/modules/both.js' {
  declare module.exports: $Exports<'rambda/modules/both'>;
}
declare module 'rambda/modules/complement.js' {
  declare module.exports: $Exports<'rambda/modules/complement'>;
}
declare module 'rambda/modules/compose.js' {
  declare module.exports: $Exports<'rambda/modules/compose'>;
}
declare module 'rambda/modules/concat.js' {
  declare module.exports: $Exports<'rambda/modules/concat'>;
}
declare module 'rambda/modules/contains.js' {
  declare module.exports: $Exports<'rambda/modules/contains'>;
}
declare module 'rambda/modules/curry.js' {
  declare module.exports: $Exports<'rambda/modules/curry'>;
}
declare module 'rambda/modules/dec.js' {
  declare module.exports: $Exports<'rambda/modules/dec'>;
}
declare module 'rambda/modules/defaultTo.js' {
  declare module.exports: $Exports<'rambda/modules/defaultTo'>;
}
declare module 'rambda/modules/dissoc.js' {
  declare module.exports: $Exports<'rambda/modules/dissoc'>;
}
declare module 'rambda/modules/divide.js' {
  declare module.exports: $Exports<'rambda/modules/divide'>;
}
declare module 'rambda/modules/drop.js' {
  declare module.exports: $Exports<'rambda/modules/drop'>;
}
declare module 'rambda/modules/dropLast.js' {
  declare module.exports: $Exports<'rambda/modules/dropLast'>;
}
declare module 'rambda/modules/either.js' {
  declare module.exports: $Exports<'rambda/modules/either'>;
}
declare module 'rambda/modules/endsWith.js' {
  declare module.exports: $Exports<'rambda/modules/endsWith'>;
}
declare module 'rambda/modules/equals.js' {
  declare module.exports: $Exports<'rambda/modules/equals'>;
}
declare module 'rambda/modules/F.js' {
  declare module.exports: $Exports<'rambda/modules/F'>;
}
declare module 'rambda/modules/filter.js' {
  declare module.exports: $Exports<'rambda/modules/filter'>;
}
declare module 'rambda/modules/find.js' {
  declare module.exports: $Exports<'rambda/modules/find'>;
}
declare module 'rambda/modules/findIndex.js' {
  declare module.exports: $Exports<'rambda/modules/findIndex'>;
}
declare module 'rambda/modules/flatten.js' {
  declare module.exports: $Exports<'rambda/modules/flatten'>;
}
declare module 'rambda/modules/flip.js' {
  declare module.exports: $Exports<'rambda/modules/flip'>;
}
declare module 'rambda/modules/forEach.js' {
  declare module.exports: $Exports<'rambda/modules/forEach'>;
}
declare module 'rambda/modules/has.js' {
  declare module.exports: $Exports<'rambda/modules/has'>;
}
declare module 'rambda/modules/head.js' {
  declare module.exports: $Exports<'rambda/modules/head'>;
}
declare module 'rambda/modules/identity.js' {
  declare module.exports: $Exports<'rambda/modules/identity'>;
}
declare module 'rambda/modules/ifElse.js' {
  declare module.exports: $Exports<'rambda/modules/ifElse'>;
}
declare module 'rambda/modules/inc.js' {
  declare module.exports: $Exports<'rambda/modules/inc'>;
}
declare module 'rambda/modules/includes.js' {
  declare module.exports: $Exports<'rambda/modules/includes'>;
}
declare module 'rambda/modules/indexOf.js' {
  declare module.exports: $Exports<'rambda/modules/indexOf'>;
}
declare module 'rambda/modules/init.js' {
  declare module.exports: $Exports<'rambda/modules/init'>;
}
declare module 'rambda/modules/internal/baseSlice.js' {
  declare module.exports: $Exports<'rambda/modules/internal/baseSlice'>;
}
declare module 'rambda/modules/is.js' {
  declare module.exports: $Exports<'rambda/modules/is'>;
}
declare module 'rambda/modules/isNil.js' {
  declare module.exports: $Exports<'rambda/modules/isNil'>;
}
declare module 'rambda/modules/join.js' {
  declare module.exports: $Exports<'rambda/modules/join'>;
}
declare module 'rambda/modules/last.js' {
  declare module.exports: $Exports<'rambda/modules/last'>;
}
declare module 'rambda/modules/lastIndexOf.js' {
  declare module.exports: $Exports<'rambda/modules/lastIndexOf'>;
}
declare module 'rambda/modules/length.js' {
  declare module.exports: $Exports<'rambda/modules/length'>;
}
declare module 'rambda/modules/map.js' {
  declare module.exports: $Exports<'rambda/modules/map'>;
}
declare module 'rambda/modules/match.js' {
  declare module.exports: $Exports<'rambda/modules/match'>;
}
declare module 'rambda/modules/merge.js' {
  declare module.exports: $Exports<'rambda/modules/merge'>;
}
declare module 'rambda/modules/modulo.js' {
  declare module.exports: $Exports<'rambda/modules/modulo'>;
}
declare module 'rambda/modules/multiply.js' {
  declare module.exports: $Exports<'rambda/modules/multiply'>;
}
declare module 'rambda/modules/none.js' {
  declare module.exports: $Exports<'rambda/modules/none'>;
}
declare module 'rambda/modules/not.js' {
  declare module.exports: $Exports<'rambda/modules/not'>;
}
declare module 'rambda/modules/omit.js' {
  declare module.exports: $Exports<'rambda/modules/omit'>;
}
declare module 'rambda/modules/partialCurry.js' {
  declare module.exports: $Exports<'rambda/modules/partialCurry'>;
}
declare module 'rambda/modules/path.js' {
  declare module.exports: $Exports<'rambda/modules/path'>;
}
declare module 'rambda/modules/pathOr.js' {
  declare module.exports: $Exports<'rambda/modules/pathOr'>;
}
declare module 'rambda/modules/pick.js' {
  declare module.exports: $Exports<'rambda/modules/pick'>;
}
declare module 'rambda/modules/pickAll.js' {
  declare module.exports: $Exports<'rambda/modules/pickAll'>;
}
declare module 'rambda/modules/pipe.js' {
  declare module.exports: $Exports<'rambda/modules/pipe'>;
}
declare module 'rambda/modules/pluck.js' {
  declare module.exports: $Exports<'rambda/modules/pluck'>;
}
declare module 'rambda/modules/prepend.js' {
  declare module.exports: $Exports<'rambda/modules/prepend'>;
}
declare module 'rambda/modules/prop.js' {
  declare module.exports: $Exports<'rambda/modules/prop'>;
}
declare module 'rambda/modules/propEq.js' {
  declare module.exports: $Exports<'rambda/modules/propEq'>;
}
declare module 'rambda/modules/range.js' {
  declare module.exports: $Exports<'rambda/modules/range'>;
}
declare module 'rambda/modules/reduce.js' {
  declare module.exports: $Exports<'rambda/modules/reduce'>;
}
declare module 'rambda/modules/reject.js' {
  declare module.exports: $Exports<'rambda/modules/reject'>;
}
declare module 'rambda/modules/repeat.js' {
  declare module.exports: $Exports<'rambda/modules/repeat'>;
}
declare module 'rambda/modules/replace.js' {
  declare module.exports: $Exports<'rambda/modules/replace'>;
}
declare module 'rambda/modules/reverse.js' {
  declare module.exports: $Exports<'rambda/modules/reverse'>;
}
declare module 'rambda/modules/sort.js' {
  declare module.exports: $Exports<'rambda/modules/sort'>;
}
declare module 'rambda/modules/sortBy.js' {
  declare module.exports: $Exports<'rambda/modules/sortBy'>;
}
declare module 'rambda/modules/split.js' {
  declare module.exports: $Exports<'rambda/modules/split'>;
}
declare module 'rambda/modules/splitEvery.js' {
  declare module.exports: $Exports<'rambda/modules/splitEvery'>;
}
declare module 'rambda/modules/startsWith.js' {
  declare module.exports: $Exports<'rambda/modules/startsWith'>;
}
declare module 'rambda/modules/subtract.js' {
  declare module.exports: $Exports<'rambda/modules/subtract'>;
}
declare module 'rambda/modules/T.js' {
  declare module.exports: $Exports<'rambda/modules/T'>;
}
declare module 'rambda/modules/tail.js' {
  declare module.exports: $Exports<'rambda/modules/tail'>;
}
declare module 'rambda/modules/take.js' {
  declare module.exports: $Exports<'rambda/modules/take'>;
}
declare module 'rambda/modules/takeLast.js' {
  declare module.exports: $Exports<'rambda/modules/takeLast'>;
}
declare module 'rambda/modules/tap.js' {
  declare module.exports: $Exports<'rambda/modules/tap'>;
}
declare module 'rambda/modules/test.js' {
  declare module.exports: $Exports<'rambda/modules/test'>;
}
declare module 'rambda/modules/times.js' {
  declare module.exports: $Exports<'rambda/modules/times'>;
}
declare module 'rambda/modules/toLower.js' {
  declare module.exports: $Exports<'rambda/modules/toLower'>;
}
declare module 'rambda/modules/toString.js' {
  declare module.exports: $Exports<'rambda/modules/toString'>;
}
declare module 'rambda/modules/toUpper.js' {
  declare module.exports: $Exports<'rambda/modules/toUpper'>;
}
declare module 'rambda/modules/trim.js' {
  declare module.exports: $Exports<'rambda/modules/trim'>;
}
declare module 'rambda/modules/type.js' {
  declare module.exports: $Exports<'rambda/modules/type'>;
}
declare module 'rambda/modules/uniq.js' {
  declare module.exports: $Exports<'rambda/modules/uniq'>;
}
declare module 'rambda/modules/uniqWith.js' {
  declare module.exports: $Exports<'rambda/modules/uniqWith'>;
}
declare module 'rambda/modules/update.js' {
  declare module.exports: $Exports<'rambda/modules/update'>;
}
declare module 'rambda/modules/values.js' {
  declare module.exports: $Exports<'rambda/modules/values'>;
}
declare module 'rambda/modules/without.js' {
  declare module.exports: $Exports<'rambda/modules/without'>;
}
declare module 'rambda/rambda.js' {
  declare module.exports: $Exports<'rambda/rambda'>;
}
declare module 'rambda/webVersion.js' {
  declare module.exports: $Exports<'rambda/webVersion'>;
}
